os: osx

osx_image: xcode11

install:
  - brew cask install powershell
  - pwsh -Command "Install-Module UnitySetup -Scope CurrentUser -Force"

script:
  - ls -al /
  - mkdir /Volumes
  - ls -al /Volumes
  - mkdir -p ~/.unitysetup
  - pwsh -Command "Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version 2018.4.6f1 -Components iOS) -Destination $HOME/Unity"
  - ls $HOME/Unity
  - $HOME/Unity/Editor/Unity -quit -batchmode -serial $UNITY_SERIAL -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD" -logFile
  - $HOME/Unity/Editor/Unity -quit -batchmode -buildTarget iOS -logFile -executeMethod UnityCIExample.Builder.BuildPlayer
  - ls -al
  - echo OK

after_script:
  - $HOME/Unity/Editor/Unity -quit -batchmode -returnlicense -logFile
