os: osx

osx_image: xcode11

install:
  - brew cask install powershell
  - pwsh -Command "Install-Module UnitySetup -Scope CurrentUser -Force"

script:
  - mkdir -p ~/.unitysetup
  - pwsh -Command "Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version 2018.4.6f1 -Components Mac,iOS) -Destination $HOME/Unity"
  - ls $HOME/Unity
  - ls $HOME/Unity/Unity.app
  - $HOME/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -serial $UNITY_SERIAL -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD" -logFile
  - $HOME/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -buildTarget iOS -logFile -executeMethod UnityCIExample.Builder.BuildPlayer
  - ls -al

after_script:
  - $HOME/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -returnlicense -logFile
