os: osx

osx_image: xcode11

install: |
  brew cask install powershell
  pwsh -Command "Install-Module UnitySetup -Scope CurrentUser -Force"

script: |
  pwsh -Command "Install-UnitySetupInstance -Installers (Find-UnitySetupInstaller -Version 2018.4.6f1 -Components Android,Windows)"
