version: 2.1

workflows:
  build:
    jobs:
      - build

executors:
  default:
    docker:
      - image: gableroux/unity3d:2018.4.6f1-android

jobs:
  build:
    parallelism: 1
    executor: default
    steps:
      - build

commands:
  build:
    description: build
    steps:
      - run:
          name: build
          command: |
            Xvfb &
            /opt/Unity/Editor/Unity -quit -batchmode -quit -serial $UNITY_SERIAL -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD" -logFile || true
            /opt/Unity/Editor/Unity -quit -batchmode -returnlicense -logFile
