version: 2.1

workflows:
  build:
    jobs:
      - build

executors:
  default:
    docker:
      - image: gableroux/unity3d:2018.4.6f1-android
    environment:
      DISPLAY: ":0"

jobs:
  build:
    parallelism: 1
    executor: default
    steps:
      - build

commands:
  build:
    description: build
    steps:
      - checkout
      - run: yes | $ANDROID_HOME/tools/bin/sdkmanager tools platform-tools "build-tools;28.0.3" "platforms;android-28"
      - run:
          name: 他のビルドが終わるまで待つ
          command: |
            apt update
            apt install -y curl jq
            # TODO: キューが100以上になるとバグるのを修正
            builds_url="https://circleci.com/api/v1.1/project/github/saturday06/UnityCIExample?circle-token=${LIMIT_CONCURRENT_BUILD_CIRCLE_TOKEN}&filter=running&limit=100"
            while [ $CIRCLE_BUILD_NUM != "$(curl $builds_url | jq '.[-1].build_num')" ]; do
              sleep 10
            done      
      - run:
          command: Xvfb -ac $DISPLAY -screen 0 640x480x16
          background: true
      - run: /opt/Unity/Editor/Unity -quit -batchmode -serial $UNITY_SERIAL -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD" -logFile
      - run: /opt/Unity/Editor/Unity -quit -batchmode -buildTarget Android -logFile -executeMethod UnityCIExample.Builder.BuildPlayer
      - run:
          when: always
          command: /opt/Unity/Editor/Unity -quit -batchmode -returnlicense -logFile
